In [6]:
import numpy as np

tmp=np.arange(12).reshape((3,2,2))
print(tmp)
indices=np.where(tmp[...,-1]<4)
print(indices)
print(tmp[indices[0],indices[1]])
tmp[indices[0],indices[1]]=0
print(tmp)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
(array([0, 0], dtype=int64), array([0, 1], dtype=int64))
[[0 1]
 [2 3]]
[[[ 0  0]
  [ 0  0]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
